// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nlpAgent.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_nlpAgent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlpAgent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_nlpAgent_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PromptRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *PromptRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type LLMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	TokensUsed    *int32                 `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3,oneof" json:"tokens_used,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMResponse) Reset() {
	*x = LLMResponse{}
	mi := &file_nlpAgent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMResponse) ProtoMessage() {}

func (x *LLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlpAgent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMResponse.ProtoReflect.Descriptor instead.
func (*LLMResponse) Descriptor() ([]byte, []int) {
	return file_nlpAgent_proto_rawDescGZIP(), []int{1}
}

func (x *LLMResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *LLMResponse) GetTokensUsed() int32 {
	if x != nil && x.TokensUsed != nil {
		return *x.TokensUsed
	}
	return 0
}

func (x *LLMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LLMResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_nlpAgent_proto protoreflect.FileDescriptor

const file_nlpAgent_proto_rawDesc = "" +
	"\n" +
	"\x0enlpAgent.proto\x12\anlAgent\"|\n" +
	"\rPromptRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\"\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05H\x00R\tmaxTokens\x88\x01\x01\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperatureB\r\n" +
	"\v_max_tokens\"\xb5\x01\n" +
	"\vLLMResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12$\n" +
	"\vtokens_used\x18\x02 \x01(\x05H\x00R\n" +
	"tokensUsed\x88\x01\x01\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\x0e\n" +
	"\f_tokens_usedB\x10\n" +
	"\x0e_error_message2E\n" +
	"\aNLAgent\x12:\n" +
	"\n" +
	"SendPrompt\x12\x16.nlAgent.PromptRequest\x1a\x14.nlAgent.LLMResponseB\x0fZ\rterminal/mainb\x06proto3"

var (
	file_nlpAgent_proto_rawDescOnce sync.Once
	file_nlpAgent_proto_rawDescData []byte
)

func file_nlpAgent_proto_rawDescGZIP() []byte {
	file_nlpAgent_proto_rawDescOnce.Do(func() {
		file_nlpAgent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nlpAgent_proto_rawDesc), len(file_nlpAgent_proto_rawDesc)))
	})
	return file_nlpAgent_proto_rawDescData
}

var file_nlpAgent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nlpAgent_proto_goTypes = []any{
	(*PromptRequest)(nil), // 0: nlAgent.PromptRequest
	(*LLMResponse)(nil),   // 1: nlAgent.LLMResponse
}
var file_nlpAgent_proto_depIdxs = []int32{
	0, // 0: nlAgent.NLAgent.SendPrompt:input_type -> nlAgent.PromptRequest
	1, // 1: nlAgent.NLAgent.SendPrompt:output_type -> nlAgent.LLMResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nlpAgent_proto_init() }
func file_nlpAgent_proto_init() {
	if File_nlpAgent_proto != nil {
		return
	}
	file_nlpAgent_proto_msgTypes[0].OneofWrappers = []any{}
	file_nlpAgent_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nlpAgent_proto_rawDesc), len(file_nlpAgent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nlpAgent_proto_goTypes,
		DependencyIndexes: file_nlpAgent_proto_depIdxs,
		MessageInfos:      file_nlpAgent_proto_msgTypes,
	}.Build()
	File_nlpAgent_proto = out.File
	file_nlpAgent_proto_goTypes = nil
	file_nlpAgent_proto_depIdxs = nil
}
