// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: nlpAgent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NLAgent_SendPrompt_FullMethodName = "/nlAgent.NLAgent/SendPrompt"
)

// NLAgentClient is the client API for NLAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NLAgentClient interface {
	SendPrompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*LLMResponse, error)
}

type nLAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNLAgentClient(cc grpc.ClientConnInterface) NLAgentClient {
	return &nLAgentClient{cc}
}

func (c *nLAgentClient) SendPrompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*LLMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLMResponse)
	err := c.cc.Invoke(ctx, NLAgent_SendPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NLAgentServer is the server API for NLAgent service.
// All implementations must embed UnimplementedNLAgentServer
// for forward compatibility.
type NLAgentServer interface {
	SendPrompt(context.Context, *PromptRequest) (*LLMResponse, error)
	mustEmbedUnimplementedNLAgentServer()
}

// UnimplementedNLAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNLAgentServer struct{}

func (UnimplementedNLAgentServer) SendPrompt(context.Context, *PromptRequest) (*LLMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrompt not implemented")
}
func (UnimplementedNLAgentServer) mustEmbedUnimplementedNLAgentServer() {}
func (UnimplementedNLAgentServer) testEmbeddedByValue()                 {}

// UnsafeNLAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NLAgentServer will
// result in compilation errors.
type UnsafeNLAgentServer interface {
	mustEmbedUnimplementedNLAgentServer()
}

func RegisterNLAgentServer(s grpc.ServiceRegistrar, srv NLAgentServer) {
	// If the following call pancis, it indicates UnimplementedNLAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NLAgent_ServiceDesc, srv)
}

func _NLAgent_SendPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLAgentServer).SendPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLAgent_SendPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLAgentServer).SendPrompt(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NLAgent_ServiceDesc is the grpc.ServiceDesc for NLAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NLAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nlAgent.NLAgent",
	HandlerType: (*NLAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPrompt",
			Handler:    _NLAgent_SendPrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nlpAgent.proto",
}
