// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: AiService.proto

package aiservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_AiService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AiService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_AiService_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_AiService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AiService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_AiService_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

var File_AiService_proto protoreflect.FileDescriptor

const file_AiService_proto_rawDesc = "" +
	"\n" +
	"\x0fAiService.proto\x12\taiservice\"(\n" +
	"\x0eCommandRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"+\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand2T\n" +
	"\tAIService\x12G\n" +
	"\x0eAnalyseRequest\x12\x19.aiservice.CommandRequest\x1a\x1a.aiservice.CommandResponseB\rZ\v./aiserviceb\x06proto3"

var (
	file_AiService_proto_rawDescOnce sync.Once
	file_AiService_proto_rawDescData []byte
)

func file_AiService_proto_rawDescGZIP() []byte {
	file_AiService_proto_rawDescOnce.Do(func() {
		file_AiService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AiService_proto_rawDesc), len(file_AiService_proto_rawDesc)))
	})
	return file_AiService_proto_rawDescData
}

var file_AiService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AiService_proto_goTypes = []any{
	(*CommandRequest)(nil),  // 0: aiservice.CommandRequest
	(*CommandResponse)(nil), // 1: aiservice.CommandResponse
}
var file_AiService_proto_depIdxs = []int32{
	0, // 0: aiservice.AIService.AnalyseRequest:input_type -> aiservice.CommandRequest
	1, // 1: aiservice.AIService.AnalyseRequest:output_type -> aiservice.CommandResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AiService_proto_init() }
func file_AiService_proto_init() {
	if File_AiService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AiService_proto_rawDesc), len(file_AiService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AiService_proto_goTypes,
		DependencyIndexes: file_AiService_proto_depIdxs,
		MessageInfos:      file_AiService_proto_msgTypes,
	}.Build()
	File_AiService_proto = out.File
	file_AiService_proto_goTypes = nil
	file_AiService_proto_depIdxs = nil
}
